# Generated by Django 2.1.7 on 2019-06-15 13:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 6, 15, 22, 9, 48, 683736), verbose_name='date published'),
        ),
    ]
