# Generated by Django 2.1.7 on 2019-06-15 21:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_comment_pub_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 6, 16, 6, 2, 2, 161059), verbose_name='date published'),
        ),
    ]
